# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ASSEMBLY_5/ASSEMBLY_5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5 || ORIG_REF_NAME==ASSEMBLY_5} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_zynq_ultra_ps_e_0_0/ASSEMBLY_5_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ASSEMBLY_5_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_xbar_1/ASSEMBLY_5_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_xbar_1 || ORIG_REF_NAME==ASSEMBLY_5_xbar_1} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_axi_interconnect_0_0/ASSEMBLY_5_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_axi_interconnect_0_0 || ORIG_REF_NAME==ASSEMBLY_5_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_smartconnect_0_0/ASSEMBLY_5_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_smartconnect_0_0 || ORIG_REF_NAME==ASSEMBLY_5_smartconnect_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_smartconnect_1_0/ASSEMBLY_5_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_smartconnect_1_0 || ORIG_REF_NAME==ASSEMBLY_5_smartconnect_1_0} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_axi_dma_0_0/ASSEMBLY_5_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_axi_dma_0_0 || ORIG_REF_NAME==ASSEMBLY_5_axi_dma_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_proc_sys_reset_0_0/ASSEMBLY_5_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_proc_sys_reset_0_0 || ORIG_REF_NAME==ASSEMBLY_5_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_axis_ann_0_1/ASSEMBLY_5_axis_ann_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_axis_ann_0_1 || ORIG_REF_NAME==ASSEMBLY_5_axis_ann_0_1} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_auto_ds_0/ASSEMBLY_5_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_auto_ds_0 || ORIG_REF_NAME==ASSEMBLY_5_auto_ds_0} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_auto_pc_0/ASSEMBLY_5_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_auto_pc_0 || ORIG_REF_NAME==ASSEMBLY_5_auto_pc_0} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_auto_ds_1/ASSEMBLY_5_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_auto_ds_1 || ORIG_REF_NAME==ASSEMBLY_5_auto_ds_1} -quiet] -quiet

# IP: bd/ASSEMBLY_5/ip/ASSEMBLY_5_auto_pc_1/ASSEMBLY_5_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_5_auto_pc_1 || ORIG_REF_NAME==ASSEMBLY_5_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_4/ASSEMBLY_4.gen/sources_1/bd/ASSEMBLY_5/ASSEMBLY_5_ooc.xdc
