# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_4/ASSEMBLY_4.srcs/sources_1/bd/ASSEMBLY_5/ip/ASSEMBLY_5_zynq_ultra_ps_e_0_0/ASSEMBLY_5_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ASSEMBLY_5_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_4/ASSEMBLY_4.gen/sources_1/bd/ASSEMBLY_5/ip/ASSEMBLY_5_zynq_ultra_ps_e_0_0/ASSEMBLY_5_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_5_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_4/ASSEMBLY_4.gen/sources_1/bd/ASSEMBLY_5/ip/ASSEMBLY_5_zynq_ultra_ps_e_0_0/ASSEMBLY_5_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_5_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_4/ASSEMBLY_4.srcs/sources_1/bd/ASSEMBLY_5/ip/ASSEMBLY_5_zynq_ultra_ps_e_0_0/ASSEMBLY_5_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ASSEMBLY_5_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_4/ASSEMBLY_4.gen/sources_1/bd/ASSEMBLY_5/ip/ASSEMBLY_5_zynq_ultra_ps_e_0_0/ASSEMBLY_5_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_5_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_4/ASSEMBLY_4.gen/sources_1/bd/ASSEMBLY_5/ip/ASSEMBLY_5_zynq_ultra_ps_e_0_0/ASSEMBLY_5_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_5_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
